# version: '3.8'

x-airflow-common: 
  &airflow-common
  image: airflow-custom:latest
  build:
    context: ./airflow
    dockerfile: Dockerfile.airflow
  environment:
    &airflow-common-env
    AIRFLOW_UID: "${AIRFLOW_UID:-50000}"
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/requirements:/opt/airflow/requirements
    - ./data/workspace:/opt/spark/data
    - spark-logs:/opt/spark/spark-events
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    airflow-redis:
      condition: service_healthy
    airflow-postgres:
      condition: service_healthy
  networks:
    - spark-network

services:

  # Setup Spark on docker
  spark-master:
    image: spark-image
    container_name: spark-master
    build:
      context: ./spark
      target: pyspark
      dockerfile: Dockerfile.spark
    entrypoint: ['./entrypoint.sh', 'master']
    env_file:
      - ./spark/.env.spark
    volumes:
      - ./data/workspace:/opt/spark/data
      - ./spark/spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - '9090:8080'     # Master UI
      - '4041:4040'     # Spark Driver
      - '7077:7077'     # Connection with Worker
    # - '15000:15000'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - spark-network


  spark-worker:
    image: spark-image
    # container_name: spark-worker
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - ./spark/.env.spark
    volumes:
      - ./data/workspace:/opt/spark/data
      - ./spark/spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    # ports:
    #   - '8081:8081'
    networks:
      - spark-network


  spark-history-server:
    image: spark-image
    container_name: spark-history
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - ./spark/.env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'   # Spark History Server UI
    networks:
      - spark-network


  spark-jupyter:
    image: spark-jupyter
    container_name: spark-jupyter
    build:
      context: ./spark
      target: jupyter-notebook
      dockerfile: Dockerfile.spark
    # depends_on:
      # spark-master:
      #   condition: service_healthy
      # spark-connect:
      #   condition: service_started
    volumes:
      - ./data/workspace:/opt/spark/data
      - ./spark/spark_apps:/opt/spark/apps
      - ./notebooks:/opt/notebooks
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'   # Jupyter Notebook
      - '4040:4040'   # Spark Driver
    networks:
      - spark-network

  # --------------------------------------------------------
  
  # Setup MinIO on docker
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio_storage:/data
    ports:
      - "9000:9000"   # API for Spark and Jupyter
      - "9001:9001"   # Console UI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - spark-network


  minio-mc:
    image: minio/mc
    container_name: minio-mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/raw-data;
      /usr/bin/mc mb myminio/processed-data;
      exit 0;
      "
    networks:
      - spark-network

  # --------------------------------------------------------

  # Setup Clickhouse on docker
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=test_db
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ./data/clickhouse_storage:/var/lib/clickhouse
    # - ./conf/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "8123:8123"   # HTTP Port   (Python/Streamlit)
      - "9009:9000"   # Native Port (DBeaver/CLI)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - spark-network

  # --------------------------------------------------------
  
  # Setup Streamlit on docker
  streamlit-dashboard:
    image: streamlit-dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard/dashboard_apps:/app
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - spark-network

  # --------------------------------------------------------

  # Setup Airflow on docker
  # 1. Airflow Database (Postgres)
  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - spark-network


  # 2. Airflow Broker (Redis)
  airflow-redis:
    image: redis:7.2-bookworm
    container_name: airflow-redis
    expose:
        - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - spark-network


  # 3. Airflow Init
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    user: "0:0"
    volumes:
      - ./airflow:/sources
      - spark-logs:/spark-logs-vol
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo "WARNING: AIRFLOW_UID not set!"
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo "WARNING: Not enough memory (Need 4GB, have $$(numfmt --to iec $$((mem_available * one_meg))))"
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo "WARNING: Not enough CPUs (Need 2, have $${cpus_available})"
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo "WARNING: Not enough Disk space (Need 10GB, have $$(numfmt --to iec $$((disk_available * 1024 ))))"
          warning_resources="true"
        fi
        echo "Fixing permissions..."
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /spark-logs-vol

        # echo "Switching to airflow user and running init..."
        # su airflow -c "/entrypoint airflow version"

        echo "Running initialization..."
        su airflow -c "/home/airflow/.local/bin/airflow db migrate"
        su airflow -c "/home/airflow/.local/bin/airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
        echo "Init completed."
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
      _AIRFLOW_WWW_USER_ROLE: Admin
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com


  # 4. Airflow Webserver (UI)
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8085:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


  # 5. Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


  # 6. Airflow Worker
  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker
    restart: always
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  # 7. Airflow Triggerer
  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  # 8. Airflow CLI
  airflow-cli:
    <<: *airflow-common
    container_name: airflow-cli
    restart: on-failure
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - |
        echo "Initializing Connections..."
        airflow connections add 'spark_default' \
          --conn-json '{
              "conn_type": "spark",
              "host": "spark://spark-master",
              "port": 7077,
              "description": "Auto-generated by docker-compose"
          }'
        
        # airflow connections add 'aws_default' ...
        
        echo "Connections created."
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


volumes:
  spark-logs:
  airflow-postgres-data:

networks:
  spark-network:
    driver: bridge